# Generated by Django 5.0.7 on 2024-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spl_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Photo')),
                ('desg', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
