# Generated by Django 5.0.7 on 2024-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='med_camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='medical_Camp')),
            ],
        ),
    ]
